Draykos
FeroxFoxxo/MQReawakened pull request #98
Opened 2024-01-12 22:56 UTC by Draykoss

- Fully implemented timed minigames. 
- Merge main

2024-01-13 15:38 UTC, FeroxFoxxo requested changes

2024-01-13 15:38 UTC, FeroxFoxxo commented on Protocols.External/[M] MinigameHandler/[G] BestResultForGroup.cs
> +            Player.TempData.ArenaModel.BestTimeForLevel = [];
If you store this in CharacterModel you can put this line in its constructor so you don't have to check for null

2024-01-13 15:38 UTC, FeroxFoxxo commented on Protocols.External/[M] MinigameHandler/[f] FinishCutscene.cs
> +        ArenaModel.LootCatalog = LootCatalog;
Maybe set this when creating the ArenaModel?

2024-01-13 15:38 UTC, FeroxFoxxo commented on Protocols.External/[M] MinigameHandler/[f] FinishCutscene.cs
> +        await Task.Delay(ArenaCatalogInt.Arena[arenaObjectId].MinigameTimeLimit);
Try inject TimerThread into your project and then using TimerThread.DelayCall instead of Task.Delay! It's non-blocking :P

2024-01-13 15:38 UTC, FeroxFoxxo commented on Protocols.External/[M] MinigameHandler/[f] FinishCutscene.cs
> +
Same as above, use TimerThread

2024-01-13 15:38 UTC, FeroxFoxxo commented on Protocols.External/[M] MinigameHandler/[f] FinishCutscene.cs
> +            if (ArenaModel.ArenaActivated || player.TempData.ArenaModel.ActivatedSwitch)
Confused why ArenaModel and player.TempData.ArenaModel are used here, just stick to one!
EDIT: Please only use player.TempData.ArenaModel or, better, create a local variable to reference this. DON'T use static to identify these variables. Static means the data will remain the same for the entire application. This means that someone attempting to try a minigame may have someone else's information.

2024-01-13 15:38 UTC, FeroxFoxxo commented on Protocols.External/[M] MinigameHandler/[f] FinishCutscene.cs
> +                ArenaModel.FinishMinigame(arenaObjectId, player);
Again, you should almost never access stuff like this statically

2024-01-13 15:38 UTC, FeroxFoxxo commented on Protocols.External/[M] MinigameHandler/[w] ReachedWaypoint.cs
> +        foreach (var player in ArenaModel.Participants)
Remember, all of these should not be accessed statically, otherwise we don't know whose arena we are dealing with!

2024-01-13 15:38 UTC, FeroxFoxxo commented on Server.Reawakened/Entities/Components/TriggerCoopArenaSwitchControllerComp.cs
> +        if (ArenaModel.ArenaActivated)
Again, don't access the arena model statically

2024-01-13 15:38 UTC, FeroxFoxxo commented on Server.Reawakened/Players/Extensions/PlayerHealExtensions.cs
> +    private static async Task HealOvertimeType(Player player, ItemDescription usedItem)
OverTime, not Overtime

2024-01-13 15:38 UTC, FeroxFoxxo commented on Server.Reawakened/Players/Extensions/PlayerHealExtensions.cs
> +        switch (usedItem.SubCategoryId)
Add a new line above switch to chunk

2024-01-13 15:38 UTC, FeroxFoxxo commented on Server.Reawakened/Players/Extensions/PlayerHealExtensions.cs
> +                await Task.Delay(1000);
Use TimerThread.DelayCall instead of Task.Delay

2024-01-13 15:38 UTC, FeroxFoxxo commented on Server.Reawakened/Players/Extensions/PlayerHealExtensions.cs
> +            await Task.Delay(3000);
TimerThread.DelayCall vs Task.Delay
Also means you wont need to make this async

2024-01-13 15:38 UTC, FeroxFoxxo commented on Server.Reawakened/Players/Extensions/PlayerHealExtensions.cs
> +            var healthAddedOvertime = itemEffectHealValue / potionDuration * 3.4;
Magic numbers, why 3.4?

2024-01-13 15:38 UTC, FeroxFoxxo commented on Server.Reawakened/Players/Models/Minigames/ArenaModel.cs
> +    public static LootCatalogInt LootCatalog { get; set; }
These should all not be static. For example, the player ids could be overwritten if a different group joins. You also initialize BestTimeForLevel in a protocol (when you check if it is null). You should initialize it, and the LootCatalog, in the ArenaModel constructor instead.

2024-01-13 15:38 UTC, FeroxFoxxo commented on Web.Launcher/Services/StartGame.cs
> +            "r",
Revert to runLauncher. Use the stash feature if you use this personally but don't want it committed.

2024-01-13 15:38 UTC, FeroxFoxxo commented on Protocols.External/[M] MinigameHandler/[G] BestResultForGroup.cs
> +        var sb = new SeparatedStringBuilder('|'); ;
Unnecessary semicolon

2024-01-13 15:38 UTC, FeroxFoxxo commented on Web.AssetBundles/Web.AssetBundles.csproj
>          <Reference Include="A2mCore">
Should use the code on the left

2024-01-20 08:21 UTC, Draykoss commented
need rework

2024-01-20 08:21 UTC, closed without merging